import { Volunteer, Event } from "./types";

export const volunteers: Volunteer[] = [
  {
    id: "vol1",
    firstName: "John",
    lastName: "Doe",
    birthCity: "Holon",
    role: [
      {
        role: { name: "paramedic" },
        isVerified: true,
      },
      {
        role: { name: "rescuer" },
        isVerified: false,
      },
    ],
    isActive: true,
  },
  {
    id: "vol2",
    firstName: "Jane",
    lastName: "Smith",
    birthCity: "Tel Aviv",
    role: [
      {
        role: { name: "first-aid-applier" },
        isVerified: true,
      },
    ],
    isActive: false,
  },
];

const events: Event[] = [
  {
    id: "event1",
    description: "Car accident at Main St.",
    location: {
      streetName: "Main St.",
      streetNumber: 123,
    },
    requires: [{ name: "paramedic" }, { name: "rescuer" }],
    volunteers: [
      {
        volunteer: volunteers[0],
        isEventAccepted: true,
      },
      {
        volunteer: volunteers[1],
        isEventAccepted: false,
      },
    ],
    time: new Date("2024-10-15T14:30:00"),
    urgency: "high",
  },
  {
    id: "event2",
    description: "Minor injury at Central Park",
    location: {
      streetName: "Central Park",
      streetNumber: 45,
    },
    requires: [{ name: "first-aid-applier" }],
    volunteers: [
      {
        volunteer: volunteers[1],
        isEventAccepted: true,
      },
    ],
    time: new Date("2024-10-16T10:00:00"),
    urgency: "low",
  },
];

export const qualifications = [
  'פרמדיק',
  'עורך דין',
  'פסיכולוג',
  'חשמלאי',
  'מחלץ',
  'שוטר',
  'מתכנת',
  'באדיבילדר',
  'סטנדאפיסט',
  'סתלבטן',
  'מגזימן',
  'א. אווירה',
  'א. מוסיקה',
  'א. נוכחות',
  'ישראל אברמוביץ',
]

export const genders = [
  "Male",
  "Female",
  "Non-binary",
  "Genderqueer",
  "Genderfluid",
  "Agender",
  "Bigender",
  "Two-Spirit",
  "Demiboy",
  "Demigirl",
  "Androgynous",
  "Intersex",
  "Pangender",
  "Gender Nonconforming",
  "Third Gender",
  "Gender Apathetic",
  "Transgender",
  "Maverique",
  "Neutrois",
  "Gendervoid",
  "Genderflux",
  "Genderfae",
  "Genderpunch",
  "Demiflux",
  "Bi-gender",
  "Polygender",
  "Graygender",
  "Ceterosexual",
  "Ceterofluid",
  "Trigender",
  "Omnigender",
  "Agenderflux",
  "Non-binary man",
  "Non-binary woman",
  "Skoliosexual",
  "Two-Spirit",
  "Intergender",
  "Aliagender",
  "Novigender",
  "Aporagender",
  "Mergender",
  "Quoigender",
  "Xenogender",
  "Gender expansive",
  "Femboy",
  "Mascagender",
  "Enby",
  "Apagender",
  "Lunagender",
  "Solarian",
  "Demi-gender",
  "Femgender",
  "Softgender",
  "Hardgender",
  "Genderfuzz",
  "Genderf*ck",
  "Gendervague",
  "Transfeminine",
  "Transmasculine",
  "Abinary",
  "Gender rebel",
  "Hijra",
  "Bakla",
  "Waria",
  "Fa'afafine",
  "Muxe",
  "Bigenus",
  "Demiboy/demigirl",
  "Trixgender",
  "Interspecies",
  "Polygenderflux",
  "Bi-genderqueer",
  "Cender",
  "Cendgender",
  "Gendermelt",
  "Gendershade",
  "Lunargender",
  "Solgender",
  "Xenogender",
  "Objectgender",
  "Affinergender",
  "Trigenderfluid",
  "Fluidgender",
  "Gendercritical",
  "Paragender",
  "Morphgender",
  "Theriangender",
  "Autigender",
  "Transgenderfluid",
  "Egender",
  "Puergender",
  "Gendermorphic",
  "Fluctuating gender",
  "Cuckoo gender",
  "Quoigender",
  "Heliogender",
  "Aeongender",
  "Introgender",
  "Biogender",
  "Sanguigender",
  "Nocturnagender",
  "Dimiagender"
];

export const days = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
]